### ISSUE TITLE
Where is the dispose in boundarycallback?

### ISSUE THREAD

**Issue by abalta** [erikcaffrey/Movies-PagingLibrary-Arch-Components#4]
Thank you for this excellent repo. But, I don't see where dispose of boundarycallback disposable.

**Comment by erikjhordan-rey** [comment]
I already fix it, thanks!
https://github.com/erikjhordan-rey/Movies-PagingLibrary-Arch-Components/blob/master/app/src/main/kotlin/io/github/erikjhordanrey/arch_components_paging_library/viewmodel/MoviesViewModel.kt
